# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

steps:

- task: TerraformInstaller@0
  displayName: 'Terraform install'
  inputs:
    terraformVersion: 'latest'

- task: TerraformTaskV3@3
  displayName: 'Terraform Init'
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'S2-Visual Studio Ultimate with MSDN(e442b2de-cb70-403f-ac05-5f1d661fb7fa)'
    backendAzureRmResourceGroupName: 'S2-RG-CORE'
    backendAzureRmStorageAccountName: 's2rgcorestorageaccount'
    backendAzureRmContainerName: 's2-rg-core-sa-container-projectmonza'
    backendAzureRmKey: 'main.tf'

- task: TerraformTaskV3@3
  displayName: 'Terraform Diffs'
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'S2-Visual Studio Ultimate with MSDN(e442b2de-cb70-403f-ac05-5f1d661fb7fa)'

- task: TerraformTaskV3@3
  displayName: 'Terraform Deploy'
  inputs:
    provider: 'azurerm'
    command: 'apply'
    environmentServiceNameAzureRM: 'S2-Visual Studio Ultimate with MSDN(e442b2de-cb70-403f-ac05-5f1d661fb7fa)'

- task: SqlAzureDacpacDeployment@1
  displayName: 'Run SQL-script'
  inputs:
    azureSubscription: 'S2-Visual Studio Ultimate with MSDN(e442b2de-cb70-403f-ac05-5f1d661fb7fa)'
    AuthenticationType: 'server'
    ServerName: 'sqlservermonzax679e6e9.database.windows.net,1433'
    DatabaseName: 'DBA42'
    SqlUsername: 'admindba'
    SqlPassword: 'ABCabc123.42'
    deployType: 'InlineSqlTask'
    SqlInline: 'dba42.sql'
    IpDetectionMethod: 'AutoDetect'