trigger:
- main

pool:
  vmImage: windows-latest

stages:
- stage: TF_DEPLOY
  jobs:
  - job:
    steps:

    - task: TerraformInstaller@0
      displayName: 'Terraform install'
      inputs:
        terraformVersion: 'latest'

    - task: TerraformTaskV3@3
      displayName: 'Terraform Init'
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'S2-Visual Studio Ultimate with MSDN(e442b2de-cb70-403f-ac05-5f1d661fb7fa)'
        backendAzureRmResourceGroupName: 'S2-RG-CORE'
        backendAzureRmStorageAccountName: 's2rgcorestorageaccount'
        backendAzureRmContainerName: 's2-rg-core-sa-container-projectmonza'
        backendAzureRmKey: 'main.tf'

    - task: TerraformTaskV3@3
      displayName: 'Terraform Diffs'
      inputs:
        provider: 'azurerm'
        command: 'plan'
        environmentServiceNameAzureRM: 'S2-Visual Studio Ultimate with MSDN(e442b2de-cb70-403f-ac05-5f1d661fb7fa)'

    - task: TerraformTaskV3@3
      displayName: 'Terraform Deploy'
      inputs:
        provider: 'azurerm'
        command: 'apply'
        environmentServiceNameAzureRM: 'S2-Visual Studio Ultimate with MSDN(e442b2de-cb70-403f-ac05-5f1d661fb7fa)'

    - task: SqlAzureDacpacDeployment@1
      displayName: 'Run SQL-scripts'
      inputs:
        azureSubscription: 'S2-Visual Studio Ultimate with MSDN(e442b2de-cb70-403f-ac05-5f1d661fb7fa)'
        AuthenticationType: 'server'
        ServerName: 'sqlservermonzax679e6e9.database.windows.net'
        DatabaseName: 'dba42'
        SqlUsername: 'admindba'
        SqlPassword: 'ABCabc123.42'
        deployType: 'SqlTask'
        SqlFile: 'dba42.sql'
        IpDetectionMethod: 'AutoDetect'

- stage: TF_DECOMMISSION
  jobs:
  - job: ApproveDecom
#    pool: server
    steps:
    - task: ManualValidation@0
      displayName: TF_Approve
      inputs:
        instructions: 'Stage TF_DECOMMISSION, do you approve?'
  - job: 
    dependsOn: ApproveDecom
    condition: Succeeded()
    steps:
    - task: TerraformInstaller@0
      displayName: 'Terraform install'
      inputs:
        terraformVersion: 'latest'

    - task: TerraformTaskV3@3
      displayName: 'Terraform Init'
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'S2-Visual Studio Ultimate with MSDN(e442b2de-cb70-403f-ac05-5f1d661fb7fa)'
        backendAzureRmResourceGroupName: 'S2-RG-CORE'
        backendAzureRmStorageAccountName: 's2rgcorestorageaccount'
        backendAzureRmContainerName: 's2-rg-core-sa-container-projectmonza'
        backendAzureRmKey: 'main.tf'

    - task: TerraformTaskV3@3
      inputs:
        provider: 'azurerm'
        command: 'destroy'
        environmentServiceNameAzureRM: 'S2-Visual Studio Ultimate with MSDN(e442b2de-cb70-403f-ac05-5f1d661fb7fa)'
