# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: TerraformInstaller@0
  displayName: 'Terraform install'
  inputs:
    terraformVersion: 'latest'

- task: TerraformTaskV3@3
  displayName: 'Terraform Init'
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'S2-Visual Studio Ultimate with MSDN(e442b2de-cb70-403f-ac05-5f1d661fb7fa)'
    backendAzureRmResourceGroupName: 'S2-RG-CORE'
    backendAzureRmStorageAccountName: 's2rgcorestorageaccount'
    backendAzureRmContainerName: 's2-rg-core-sa-container-projectmonza'
    backendAzureRmKey: 'main.tf'